version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  gopref:
    image: gopref
    container_name: gopref
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - 4000:4000
    volumes:
      - ./tmp:/app/tmp
  web:
    image: nginx
    container_name: nginx
    depends_on:
      - gopref
    volumes:
      - ./ssl/advpls.com.pem:/etc/ssl/advpls.com.pem
      - ./ssl/advpls.com.key:/etc/ssl/advpls.com.key
      - ./gopref-nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/home/gopref/dist
    ports:
      - 443:443
