version: '3'
services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      gpnet:
        ipv4_address: 10.1.0.100
  gopref:
    image: gopref
    container_name: gopref
    restart: on-failure
    expose:
      - 4000
    volumes:
      - ./tmp:/app/tmp
    networks:
      gopref:
        ipv4_address: 10.1.0.101
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./ssl/advpls.com.pem:/etc/ssl/advpls.com.pem
      - ./ssl/advpls.com.key:/etc/ssl/advpls.com.key
      - ./gopref-nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/home/gopref/dist
    ports:
      - 443:443
    networks:
      gpnet:
        ipv4_address: 10.1.0.102
networks:
  gpnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
